#Imprimir título
print("Programa para calcular la nota promedio de los estudiantes:")
Estudiante_1=(input("Ingresar nombre 1:"))
Estudiante_2=(input("Ingresar nombre 2:"))
Estudiante_3=(input("Ingresar nombre 3:"))
Estudiante_4=(input("Ingresar nombre 4:"))
Estudiante_5=(input("Ingresar nombre 5:"))
Edad_1=int(input("Ingresar edad 1:"))
Edad_2=int(input("Ingresar edad 2:"))
Edad_3=int(input("Ingresar edad 3:"))
Edad_4=int(input("Ingresar edad 4:"))
Edad_5=int(input("Ingresar edad 5:"))
Nota_1=float(input("ingresar Nota 1:"))
Nota_2=float(input("Ingresar Nota 2:"))
Nota_3=float(input("Ingresar Nota 3:"))
Nota_4=float(input("Ingresar Nota 4:"))
Nota_5=float(input("Ingresar Nota 5:"))
Nota_Promedio=5/5
print("La nota promedio es:" , Nota_Promedio)
